//This file is responsible for giving the user,
//the choices for the notes that come along with the activity
export const notes = [
    { key: 'Δεν υπάρχει σχετική', text: 'Δεν υπάρχει σχετική', value: 'Δεν υπάρχει σχετική' },
    { key: 'McAffee Agent στο MIS', text: 'McAffee Agent στο MIS', value: 'McAffee Agent στο MIS' },
    { key: 'Policy instant Update', text: 'Policy instant Update', value: 'Policy instant Update' },
    { key: 'Εγκατάσταση Dude', text: 'Εγκατάσταση Dude', value: 'Εγκατάσταση Dude' },
    { key: 'Ίντερνετ Λέσχης', text: 'Ίντερνετ Λέσχης', value: 'Ίντερνετ Λέσχης' },
    { key: 'Πρόβλημα με IP', text: 'Πρόβλημα με IP', value: 'Πρόβλημα με IP' },
    { key: 'Σύνδεση σε server', text: 'Σύνδεση σε server', value: 'Σύνδεση σε server' },
    { key: 'Δημιουργία καλωδίου δικτύου', text: 'Δημιουργία καλωδίου δικτύου', value: 'Δημιουργία καλωδίου δικτύου' },
    { key: 'Απομακρυσμένο άνοιγμα δίσκου C', text: 'Απομακρυσμένο άνοιγμα δίσκου C', value: 'Απομακρυσμένο άνοιγμα δίσκου C' },
    { key: 'Switches Password', text: 'Switches Password', value: 'Switches Password' },
    { key: 'Deep refresh', text: 'Deep refresh', value: 'Deep refresh' },
    { key: 'Disk cleanup / Partion cleanup', text: 'Disk cleanup / Partion cleanup', value: 'Disk cleanup / Partion cleanup' },
    { key: 'Λογαριασμοί internet', text: 'Λογαριασμοί internet', value: 'Λογαριασμοί internet' },
    { key: 'Κλείδωμα υπολογιστή', text: 'Κλείδωμα υπολογιστή', value: 'Κλείδωμα υπολογιστή' },
    { key: 'Εξωτερικό email', text: 'Εξωτερικό email', value: 'Εξωτερικό email' },
    { key: 'MIS Λογαριασμοί και email', text: 'MIS Λογαριασμοί και email', value: 'MIS Λογαριασμοί και email' },
    { key: 'Κωδικός BIOS', text: 'Κωδικός BIOS', value: 'Κωδικός BIOS' },
    { key: 'Σύστημα καμερών', text: 'Σύστημα καμερών', value: 'Σύστημα καμερών' },
    { key: 'VTC', text: 'VTC', value: 'VTC' },
    { key: 'Apollo', text: 'Apollo', value: 'Apollo' },
    { key: 'Professional right click', text: 'Professional right click', value: 'Professional right click' },
    { key: 'Σχέση εμπιστοσύνης', text: 'Σχέση εμπιστοσύνης', value: 'Σχέση εμπιστοσύνης' },
    { key: 'Blind outside 114pm', text: 'Blind outside 114pm', value: 'Blind outside 114pm' },
    { key: 'Διαχείριση / Κόλλημα ίντερνετ', text: 'Διαχείριση / Κόλλημα ίντερνετ', value: 'Διαχείριση / Κόλλημα ίντερνετ' },
    { key: 'WiFi γραφείου', text: 'WiFi γραφείου', value: 'WiFi γραφείου' },
    { key: 'Σύνδεση εκτυπωτή', text: 'Σύνδεση εκτυπωτή', value: 'Σύνδεση εκτυπωτή' },
    { key: 'Σύνδεση PC στο MIS', text: 'Σύνδεση PC στο MIS', value: 'Σύνδεση PC στο MIS' },
    { key: 'Infinite Ping', text: 'Infinite Ping', value: 'Infinite Ping' },
    { key: 'Εύρεση Computer name & IP', text: 'Εύρεση Computer name & IP', value: 'Εύρεση Computer name & IP' },
    { key: 'Λογαριασμοί ΗΣΑ', text: 'Λογαριασμοί ΗΣΑ', value: 'Λογαριασμοί ΗΣΑ' },
    { key: 'Helpdesks', text: 'Helpdesks', value: 'Helpdesks' },
    { key: 'CCIS', text: 'CCIS', value: 'CCIS' },
];
  